version: '3'

services:
  akash-api-proxy:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_PREFIX=/
      - API_KEY=your_api_key
      - SESSION_TOKEN=your_session_token
      - PORT=8000
      - BASE_URL=http://localhost:8000
    restart: always
